version: '3.9'
services:
  probot-db:
    image: postgres:13
    restart: always
    volumes:
      - ${PWD}/.probot-build/database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=probot
      - POSTGRES_PASSWORD=probot
  probot-builder:
    build:
      context: .
      args:
        - SCOPE=builder
    depends_on:
      - probot-db
    ports:
      - '8080:3000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    env_file: .env
  probot-viewer:
    build:
      context: .
      args:
        - SCOPE=viewer
    ports:
      - '8081:3000'
    env_file: .env
